version: 2
updates:
  - package-ecosystem: "maven"
    directory: "Snak/.github"   # Pfad zur pom.xml
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"